package main

// 型号与协议资料固定于 OpenRazer master（2026-09-28 在线核对）。
// PID / 名称：driver/*_driver.h、*_driver.c 的 USB 表和 device_type；
// 类别：daemon/openrazer_daemon/hardware；电量：charge_level 属性绑定与处理函数的交集。
// 鼠标能力边界与型号清单见 ../docs/MOUSE_PROTOCOL.md。
const catalogSourceCommit = "6820f9da169d354bc7e6e93a0aa8683a6bb75792"

type modelInfo struct {
	Name       string
	Kind       string
	Connection string
	Battery    bool // 仅启用已核对的 class 07 / command 80 电量查询。
	TID        byte
	Scale255   bool // 固定按型号选择刻度，不能根据一次读数是否超过100猜测。
	NoCharge   bool // 上游明确直接返回未充电，不发送 command 84。
	WaitMillis int  // 电量查询发送和接收之间的最短等待时间。
}

var models = map[uint16]modelInfo{
	0x0013: {Name: "Razer Orochi 2011", Kind: "鼠标", Connection: "USB"},
	0x0015: {Name: "Razer Naga", Kind: "鼠标", Connection: "USB"},
	0x0016: {Name: "Razer DeathAdder 3.5G", Kind: "鼠标", Connection: "USB"},
	0x001F: {Name: "Razer Naga Epic", Kind: "鼠标", Connection: "USB", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0020: {Name: "Razer Abyssus 1800", Kind: "鼠标", Connection: "USB"},
	0x0024: {Name: "Razer Mamba 2012 (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0025: {Name: "Razer Mamba 2012 (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0029: {Name: "Razer DeathAdder 3.5G Black", Kind: "鼠标", Connection: "USB"},
	0x002E: {Name: "Razer Naga 2012", Kind: "鼠标", Connection: "USB"},
	0x002F: {Name: "Razer Imperator 2012", Kind: "鼠标", Connection: "USB"},
	0x0032: {Name: "Razer Ouroboros", Kind: "鼠标", Connection: "USB", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0034: {Name: "Razer Taipan", Kind: "鼠标", Connection: "USB"},
	0x0036: {Name: "Razer Naga Hex (Red)", Kind: "鼠标", Connection: "USB"},
	0x0037: {Name: "Razer DeathAdder 2013", Kind: "鼠标", Connection: "USB"},
	0x0038: {Name: "Razer DeathAdder 1800", Kind: "鼠标", Connection: "USB"},
	0x0039: {Name: "Razer Orochi 2013", Kind: "鼠标", Connection: "USB"},
	0x003E: {Name: "Razer Naga Epic Chroma", Kind: "鼠标", Connection: "USB", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x003F: {Name: "Razer Naga Epic Chroma Dock", Kind: "鼠标", Connection: "USB", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0040: {Name: "Razer Naga 2014", Kind: "鼠标", Connection: "USB"},
	0x0041: {Name: "Razer Naga Hex", Kind: "鼠标", Connection: "USB"},
	0x0042: {Name: "Razer Abyssus 2014", Kind: "鼠标", Connection: "USB"},
	0x0043: {Name: "Razer DeathAdder Chroma", Kind: "鼠标", Connection: "USB"},
	0x0044: {Name: "Razer Mamba (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0045: {Name: "Razer Mamba (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 35},
	0x0046: {Name: "Razer Mamba Tournament Edition", Kind: "鼠标", Connection: "有线"},
	0x0048: {Name: "Razer Orochi (Wired)", Kind: "鼠标", Connection: "有线"},
	0x004C: {Name: "Razer Diamondback Chroma", Kind: "鼠标", Connection: "USB"},
	0x004F: {Name: "Razer DeathAdder 2000", Kind: "鼠标", Connection: "USB"},
	0x0050: {Name: "Razer Naga Hex V2", Kind: "鼠标", Connection: "USB"},
	0x0053: {Name: "Razer Naga Chroma", Kind: "鼠标", Connection: "USB"},
	0x0054: {Name: "Razer DeathAdder 3500", Kind: "鼠标", Connection: "USB"},
	0x0059: {Name: "Razer Lancehead (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 35},
	0x005A: {Name: "Razer Lancehead (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 35},
	0x005B: {Name: "Razer Abyssus V2", Kind: "鼠标", Connection: "USB"},
	0x005C: {Name: "Razer DeathAdder Elite", Kind: "鼠标", Connection: "USB"},
	0x005E: {Name: "Razer Abyssus 2000", Kind: "鼠标", Connection: "USB"},
	0x0060: {Name: "Razer Lancehead Tournament Edition", Kind: "鼠标", Connection: "有线"},
	0x0062: {Name: "Razer Atheris (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 405},
	0x0064: {Name: "Razer Basilisk", Kind: "鼠标", Connection: "USB"},
	0x0065: {Name: "Razer Basilisk Essential", Kind: "鼠标", Connection: "USB"},
	0x0067: {Name: "Razer Naga Trinity", Kind: "鼠标", Connection: "USB"},
	0x0068: {Name: "Razer Firefly Hyperflux", Kind: "配件", Connection: "USB"},
	0x006A: {Name: "Razer Abyssus Elite (D.Va Edition)", Kind: "鼠标", Connection: "USB"},
	0x006B: {Name: "Razer Abyssus Essential", Kind: "鼠标", Connection: "USB"},
	0x006C: {Name: "Razer Mamba Elite", Kind: "鼠标", Connection: "USB"},
	0x006E: {Name: "Razer DeathAdder Essential", Kind: "鼠标", Connection: "USB"},
	0x006F: {Name: "Razer Lancehead Wireless (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0070: {Name: "Razer Lancehead Wireless (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0071: {Name: "Razer DeathAdder Essential (White Edition)", Kind: "鼠标", Connection: "USB"},
	0x0072: {Name: "Razer Mamba Wireless (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 35},
	0x0073: {Name: "Razer Mamba Wireless (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 35},
	0x0077: {Name: "Razer Pro Click (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0078: {Name: "Razer Viper", Kind: "鼠标", Connection: "USB"},
	0x007A: {Name: "Razer Viper Ultimate (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 60},
	0x007B: {Name: "Razer Viper Ultimate (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0xFF, Scale255: true, WaitMillis: 60},
	0x007C: {Name: "Razer DeathAdder V2 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 60},
	0x007D: {Name: "Razer DeathAdder V2 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 60},
	0x007E: {Name: "Razer Mouse Dock", Kind: "配件", Connection: "USB"},
	0x0080: {Name: "Razer Pro Click (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0083: {Name: "Razer Basilisk X HyperSpeed", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0xFF, Scale255: true, NoCharge: true, WaitMillis: 35},
	0x0084: {Name: "Razer DeathAdder V2", Kind: "鼠标", Connection: "USB"},
	0x0085: {Name: "Razer Basilisk V2", Kind: "鼠标", Connection: "USB"},
	0x0086: {Name: "Razer Basilisk Ultimate (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0088: {Name: "Razer Basilisk Ultimate (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x008A: {Name: "Razer Viper Mini", Kind: "鼠标", Connection: "USB"},
	0x008C: {Name: "Razer DeathAdder V2 Mini", Kind: "鼠标", Connection: "USB"},
	0x008D: {Name: "Razer Naga Left-Handed Edition 2020", Kind: "鼠标", Connection: "USB"},
	0x008F: {Name: "Razer Naga Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0090: {Name: "Razer Naga Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0091: {Name: "Razer Viper 8KHz", Kind: "鼠标", Connection: "USB"},
	0x0094: {Name: "Razer Orochi V2 (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 405},
	0x0095: {Name: "Razer Orochi V2 (Bluetooth)", Kind: "鼠标", Connection: "USB", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 405},
	0x0096: {Name: "Razer Naga X", Kind: "鼠标", Connection: "USB"},
	0x0098: {Name: "Razer DeathAdder Essential (2021)", Kind: "鼠标", Connection: "USB"},
	0x0099: {Name: "Razer Basilisk V3", Kind: "鼠标", Connection: "USB"},
	0x009A: {Name: "Razer Pro Click Mini (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x009C: {Name: "Razer DeathAdder V2 X HyperSpeed", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 35},
	0x009E: {Name: "Razer Viper Mini Signature Edition (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 60},
	0x009F: {Name: "Razer Viper Mini Signature Edition (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 60},
	0x00A1: {Name: "Razer DeathAdder V2 Lite", Kind: "鼠标", Connection: "USB"},
	0x00A3: {Name: "Razer Cobra", Kind: "鼠标", Connection: "USB"},
	0x00A4: {Name: "Razer Mouse Dock Pro", Kind: "配件", Connection: "USB"},
	0x00A5: {Name: "Razer Viper V2 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00A6: {Name: "Razer Viper V2 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00A7: {Name: "Razer Naga V2 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00A8: {Name: "Razer Naga V2 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00AA: {Name: "Razer Basilisk V3 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00AB: {Name: "Razer Basilisk V3 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00AF: {Name: "Razer Cobra Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00B0: {Name: "Razer Cobra Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00B2: {Name: "Razer DeathAdder V3", Kind: "鼠标", Connection: "USB"},
	0x00B3: {Name: "Razer HyperPolling Wireless Dongle", Kind: "配件", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 60},
	0x00B4: {Name: "Razer Naga V2 HyperSpeed (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 35},
	0x00B6: {Name: "Razer DeathAdder V3 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00B7: {Name: "Razer DeathAdder V3 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00B8: {Name: "Razer Viper V3 HyperSpeed", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 60},
	0x00B9: {Name: "Razer Basilisk V3 X HyperSpeed", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 35},
	0x00BE: {Name: "Razer DeathAdder V4 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00BF: {Name: "Razer DeathAdder V4 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C0: {Name: "Razer Viper V3 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C1: {Name: "Razer Viper V3 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 60},
	0x00C2: {Name: "Razer DeathAdder V3 Pro (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C3: {Name: "Razer DeathAdder V3 Pro (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C4: {Name: "Razer DeathAdder V3 HyperSpeed (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C5: {Name: "Razer DeathAdder V3 HyperSpeed (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C7: {Name: "Razer Pro Click V2 Vertical Edition (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00C8: {Name: "Razer Pro Click V2 Vertical Edition (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00CB: {Name: "Razer Basilisk V3 35K", Kind: "鼠标", Connection: "USB"},
	0x00CC: {Name: "Razer Basilisk V3 Pro 35K (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00CD: {Name: "Razer Basilisk V3 Pro 35K (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00D0: {Name: "Razer Pro Click V2 (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00D1: {Name: "Razer Pro Click V2 (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00D3: {Name: "Razer Basilisk Mobile (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 35},
	0x00D4: {Name: "Razer Basilisk Mobile (Receiver)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, NoCharge: true, WaitMillis: 35},
	0x00D6: {Name: "Razer Basilisk V3 Pro 35K Phantom Green Edition (Wired)", Kind: "鼠标", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x00D7: {Name: "Razer Basilisk V3 Pro 35K Phantom Green Edition (Wireless)", Kind: "鼠标", Connection: "无线接收器", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x010D: {Name: "Razer BlackWidow Ultimate 2012", Kind: "键盘", Connection: "USB"},
	0x010E: {Name: "Razer BlackWidow Stealth Edition", Kind: "键盘", Connection: "USB"},
	0x010F: {Name: "Razer Anansi", Kind: "键盘", Connection: "USB"},
	0x0111: {Name: "Razer Nostromo", Kind: "键盘", Connection: "USB"},
	0x0113: {Name: "Razer Orbweaver", Kind: "键盘", Connection: "USB"},
	0x0118: {Name: "Razer Deathstalker (Essential)", Kind: "键盘", Connection: "USB"},
	0x011A: {Name: "Razer BlackWidow Ultimate 2013", Kind: "键盘", Connection: "USB"},
	0x011B: {Name: "Razer BlackWidow Stealth", Kind: "键盘", Connection: "USB"},
	0x011C: {Name: "Razer BlackWidow Tournament Edition 2014", Kind: "键盘", Connection: "USB"},
	0x0201: {Name: "Razer Tartarus", Kind: "键盘", Connection: "USB"},
	0x0202: {Name: "Razer Deathstalker Expert", Kind: "键盘", Connection: "USB"},
	0x0203: {Name: "Razer BlackWidow Chroma", Kind: "键盘", Connection: "USB"},
	0x0204: {Name: "Razer DeathStalker Chroma", Kind: "键盘", Connection: "USB"},
	0x0205: {Name: "Razer Blade Stealth", Kind: "键盘", Connection: "USB"},
	0x0207: {Name: "Razer Orbweaver Chroma", Kind: "键盘", Connection: "USB"},
	0x0208: {Name: "Razer Tartarus Chroma", Kind: "键盘", Connection: "USB"},
	0x0209: {Name: "Razer BlackWidow Chroma Tournament Edition", Kind: "键盘", Connection: "USB"},
	0x020F: {Name: "Razer Blade Stealth (QHD)", Kind: "键盘", Connection: "USB"},
	0x0210: {Name: "Razer Blade Pro (Late 2016)", Kind: "键盘", Connection: "USB"},
	0x0211: {Name: "Razer BlackWidow Chroma (Overwatch)", Kind: "键盘", Connection: "USB"},
	0x0214: {Name: "Razer BlackWidow Ultimate 2016", Kind: "键盘", Connection: "USB"},
	0x0215: {Name: "Razer Core", Kind: "配件", Connection: "USB"},
	0x0216: {Name: "Razer BlackWidow X Chroma", Kind: "键盘", Connection: "USB"},
	0x0217: {Name: "Razer BlackWidow X Ultimate", Kind: "键盘", Connection: "USB"},
	0x021A: {Name: "Razer BlackWidow X Chroma Tournament Edition", Kind: "键盘", Connection: "USB"},
	0x021E: {Name: "Razer Ornata Chroma", Kind: "键盘", Connection: "USB"},
	0x021F: {Name: "Razer Ornata", Kind: "键盘", Connection: "USB"},
	0x0220: {Name: "Razer Blade Stealth (Late 2016)", Kind: "键盘", Connection: "USB"},
	0x0221: {Name: "Razer BlackWidow Chroma V2", Kind: "键盘", Connection: "USB"},
	0x0224: {Name: "Razer Blade (Late 2016)", Kind: "键盘", Connection: "USB"},
	0x0225: {Name: "Razer Blade Pro (2017)", Kind: "键盘", Connection: "USB"},
	0x0226: {Name: "Razer Huntsman Elite", Kind: "键盘", Connection: "USB"},
	0x0227: {Name: "Razer Huntsman", Kind: "键盘", Connection: "USB"},
	0x0228: {Name: "Razer BlackWidow Elite", Kind: "键盘", Connection: "USB"},
	0x022A: {Name: "Razer Cynosa Chroma", Kind: "键盘", Connection: "USB"},
	0x022B: {Name: "Razer Tartarus V2", Kind: "键盘", Connection: "USB"},
	0x022C: {Name: "Razer Cynosa Chroma Pro", Kind: "键盘", Connection: "USB"},
	0x022D: {Name: "Razer Blade Stealth (Mid 2017)", Kind: "键盘", Connection: "USB"},
	0x022F: {Name: "Razer Blade Pro FullHD (2017)", Kind: "键盘", Connection: "USB"},
	0x0232: {Name: "Razer Blade Stealth (Late 2017)", Kind: "键盘", Connection: "USB"},
	0x0233: {Name: "Razer Blade 15 (2018)", Kind: "键盘", Connection: "USB"},
	0x0234: {Name: "Razer Blade Pro (2019)", Kind: "键盘", Connection: "USB"},
	0x0235: {Name: "Razer BlackWidow Lite", Kind: "键盘", Connection: "USB"},
	0x0237: {Name: "Razer BlackWidow Essential", Kind: "键盘", Connection: "USB"},
	0x0239: {Name: "Razer Blade Stealth (2019)", Kind: "键盘", Connection: "USB"},
	0x023A: {Name: "Razer Blade 15 (2019) Advanced", Kind: "键盘", Connection: "USB"},
	0x023B: {Name: "Razer Blade 15 (2018) Base Model", Kind: "键盘", Connection: "USB"},
	0x023F: {Name: "Razer Cynosa Lite", Kind: "键盘", Connection: "USB"},
	0x0240: {Name: "Razer Blade 15 (2018) Mercury", Kind: "键盘", Connection: "USB"},
	0x0241: {Name: "Razer BlackWidow 2019", Kind: "键盘", Connection: "USB"},
	0x0243: {Name: "Razer Huntsman Tournament Edition", Kind: "键盘", Connection: "USB"},
	0x0244: {Name: "Razer Tartarus Pro", Kind: "键盘", Connection: "USB"},
	0x0245: {Name: "Razer Blade 15 (Mid 2019) Mercury White", Kind: "键盘", Connection: "USB"},
	0x0246: {Name: "Razer Blade 15 (2019) Base Model", Kind: "键盘", Connection: "USB"},
	0x024A: {Name: "Razer Blade Stealth (Late 2019)", Kind: "键盘", Connection: "USB"},
	0x024B: {Name: "Razer Blade Advanced (Late 2019)", Kind: "键盘", Connection: "USB"},
	0x024C: {Name: "Razer Blade Pro (Late 2019)", Kind: "键盘", Connection: "USB"},
	0x024D: {Name: "Razer Blade 15 Studio Edition (2019)", Kind: "键盘", Connection: "USB"},
	0x024E: {Name: "Razer BlackWidow V3", Kind: "键盘", Connection: "USB"},
	0x0252: {Name: "Razer Blade Stealth (Early 2020)", Kind: "键盘", Connection: "USB"},
	0x0253: {Name: "Razer Blade 15 Advanced (2020)", Kind: "键盘", Connection: "USB"},
	0x0255: {Name: "Razer Blade 15 Base (Early 2020)", Kind: "键盘", Connection: "USB"},
	0x0256: {Name: "Razer Blade Pro (Early 2020)", Kind: "键盘", Connection: "USB"},
	0x0257: {Name: "Razer Huntsman Mini", Kind: "键盘", Connection: "USB"},
	0x0258: {Name: "Razer BlackWidow V3 Mini HyperSpeed (Wired)", Kind: "键盘", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0259: {Name: "Razer Blade Stealth (Late 2020)", Kind: "键盘", Connection: "USB"},
	0x025A: {Name: "Razer BlackWidow V3 Pro (Wired)", Kind: "键盘", Connection: "有线", Battery: true, TID: 0x3F, Scale255: true, WaitMillis: 35},
	0x025C: {Name: "Razer BlackWidow V3 Pro (Wireless)", Kind: "键盘", Connection: "无线接收器", Battery: true, TID: 0x9F, Scale255: true, WaitMillis: 35},
	0x025D: {Name: "Razer Ornata V2", Kind: "键盘", Connection: "USB"},
	0x025E: {Name: "Razer Cynosa V2", Kind: "键盘", Connection: "USB"},
	0x0266: {Name: "Razer Huntsman V2 Analog", Kind: "键盘", Connection: "USB"},
	0x0268: {Name: "Razer Blade 15 Base (Late 2020)", Kind: "键盘", Connection: "USB"},
	0x0269: {Name: "Razer Huntsman Mini (JP)", Kind: "键盘", Connection: "USB"},
	0x026A: {Name: "Razer Book 13 (2020)", Kind: "键盘", Connection: "USB"},
	0x026B: {Name: "Razer Huntsman V2 Tenkeyless", Kind: "键盘", Connection: "USB"},
	0x026C: {Name: "Razer Huntsman V2", Kind: "键盘", Connection: "USB"},
	0x026D: {Name: "Razer Blade 15 Advanced (Early 2021)", Kind: "键盘", Connection: "USB"},
	0x026E: {Name: "Razer Blade 17 Pro (Early 2021)", Kind: "键盘", Connection: "USB"},
	0x026F: {Name: "Razer Blade 15 Base (Early 2021)", Kind: "键盘", Connection: "USB"},
	0x0270: {Name: "Razer Blade 14 (2021)", Kind: "键盘", Connection: "USB"},
	0x0271: {Name: "Razer BlackWidow V3 Mini HyperSpeed (Wireless)", Kind: "键盘", Connection: "无线接收器", Battery: true, TID: 0x9F, Scale255: true, WaitMillis: 35},
	0x0276: {Name: "Razer Blade 15 Advanced (Mid 2021)", Kind: "键盘", Connection: "USB"},
	0x0279: {Name: "Razer Blade 17 Pro (Mid 2021)", Kind: "键盘", Connection: "USB"},
	0x027A: {Name: "Razer Blade 15 Base (2022)", Kind: "键盘", Connection: "USB"},
	0x0282: {Name: "Razer Huntsman Mini Analog", Kind: "键盘", Connection: "USB"},
	0x0287: {Name: "Razer BlackWidow V4", Kind: "键盘", Connection: "USB"},
	0x028A: {Name: "Razer Blade 15 Advanced (Early 2022)", Kind: "键盘", Connection: "USB"},
	0x028B: {Name: "Razer Blade 17 (2022)", Kind: "键盘", Connection: "USB"},
	0x028C: {Name: "Razer Blade 14 (2022)", Kind: "键盘", Connection: "USB"},
	0x028D: {Name: "Razer BlackWidow V4 Pro", Kind: "键盘", Connection: "USB"},
	0x028F: {Name: "Razer Ornata V3", Kind: "键盘", Connection: "USB"},
	0x0290: {Name: "Razer DeathStalker V2 Pro (Wireless)", Kind: "键盘", Connection: "无线接收器", Battery: true, TID: 0x9F, Scale255: true, WaitMillis: 35},
	0x0292: {Name: "Razer DeathStalker V2 Pro (Wired)", Kind: "键盘", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0293: {Name: "Razer BlackWidow V4 X", Kind: "键盘", Connection: "USB"},
	0x0294: {Name: "Razer Ornata V3 X", Kind: "键盘", Connection: "USB"},
	0x0295: {Name: "Razer DeathStalker V2", Kind: "键盘", Connection: "USB"},
	0x0296: {Name: "Razer DeathStalker V2 Pro TKL (Wireless)", Kind: "键盘", Connection: "无线接收器", Battery: true, TID: 0x9F, Scale255: true, WaitMillis: 35},
	0x0298: {Name: "Razer DeathStalker V2 Pro TKL (Wired)", Kind: "键盘", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x029D: {Name: "Razer Blade 14 (2023)", Kind: "键盘", Connection: "USB"},
	0x029E: {Name: "Razer Blade 15 (2023)", Kind: "键盘", Connection: "USB"},
	0x029F: {Name: "Razer Blade 16 (2023)", Kind: "键盘", Connection: "USB"},
	0x02A0: {Name: "Razer Blade 18 (2023)", Kind: "键盘", Connection: "USB"},
	0x02A1: {Name: "Razer Ornata V3", Kind: "键盘", Connection: "USB"},
	0x02A2: {Name: "Razer Ornata V3 X", Kind: "键盘", Connection: "USB"},
	0x02A3: {Name: "Razer Ornata V3 Tenkeyless", Kind: "键盘", Connection: "USB"},
	0x02A5: {Name: "Razer BlackWidow V4 75%", Kind: "键盘", Connection: "USB"},
	0x02A6: {Name: "Razer Huntsman V3 Pro", Kind: "键盘", Connection: "USB"},
	0x02A7: {Name: "Razer Huntsman V3 Pro TKL", Kind: "键盘", Connection: "USB"},
	0x02B0: {Name: "Razer Huntsman V3 Pro Mini", Kind: "键盘", Connection: "USB"},
	0x02B6: {Name: "Razer Blade 14 (2024)", Kind: "键盘", Connection: "USB"},
	0x02B8: {Name: "Razer Blade 18 (2024)", Kind: "键盘", Connection: "USB"},
	0x02B9: {Name: "Razer BlackWidow V4 Mini Hyperspeed (Wired)", Kind: "键盘", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x02BA: {Name: "Razer BlackWidow V4 Mini Hyperspeed (Wireless)", Kind: "键盘", Connection: "无线接收器", Battery: true, TID: 0x9F, Scale255: true, WaitMillis: 35},
	0x02C5: {Name: "Razer Blade 14 (2025)", Kind: "键盘", Connection: "USB"},
	0x02C6: {Name: "Razer Blade 16 (2025)", Kind: "键盘", Connection: "USB"},
	0x02C7: {Name: "Razer Blade 18 (2025)", Kind: "键盘", Connection: "USB"},
	0x02CF: {Name: "Razer Huntsman V3 Pro 8KHz", Kind: "键盘", Connection: "USB"},
	0x02D5: {Name: "Razer BlackWidow V4 Tenkeyless HyperSpeed (Wireless)", Kind: "键盘", Connection: "无线接收器", Battery: true, TID: 0x9F, Scale255: true, WaitMillis: 35},
	0x02D7: {Name: "Razer BlackWidow V4 Tenkeyless HyperSpeed (Wired)", Kind: "键盘", Connection: "有线", Battery: true, TID: 0x1F, Scale255: true, WaitMillis: 35},
	0x0501: {Name: "Razer Kraken 7.1", Kind: "耳机", Connection: "USB"},
	0x0504: {Name: "Razer Kraken 7.1 Chroma", Kind: "耳机", Connection: "USB"},
	0x0506: {Name: "Razer Kraken 7.1", Kind: "耳机", Connection: "USB"},
	0x0510: {Name: "Razer Kraken 7.1 V2", Kind: "耳机", Connection: "USB"},
	0x0517: {Name: "Razer Nommo Chroma", Kind: "配件", Connection: "USB"},
	0x0518: {Name: "Razer Nommo Pro", Kind: "配件", Connection: "USB"},
	0x0520: {Name: "Razer Kraken Tournament Edition", Kind: "耳机", Connection: "USB"},
	0x0527: {Name: "Razer Kraken Ultimate", Kind: "耳机", Connection: "USB"},
	0x0560: {Name: "Razer Kraken Kitty V2", Kind: "耳机", Connection: "USB"},
	0x0A24: {Name: "Razer BlackWidow V3 Tenkeyless", Kind: "键盘", Connection: "USB"},
	0x0C00: {Name: "Razer Firefly", Kind: "配件", Connection: "USB"},
	0x0C01: {Name: "Razer Goliathus", Kind: "配件", Connection: "USB"},
	0x0C02: {Name: "Razer Goliathus Extended", Kind: "配件", Connection: "USB"},
	0x0C04: {Name: "Razer Firefly V2", Kind: "配件", Connection: "USB"},
	0x0C05: {Name: "Razer Strider Chroma", Kind: "配件", Connection: "USB"},
	0x0C06: {Name: "Razer Goliathus Chroma 3XL", Kind: "配件", Connection: "USB"},
	0x0C08: {Name: "Razer Firefly V2 Pro", Kind: "配件", Connection: "USB"},
	0x0F07: {Name: "Razer Chroma Mug Holder", Kind: "配件", Connection: "USB"},
	0x0F08: {Name: "Razer Base Station Chroma", Kind: "配件", Connection: "USB"},
	0x0F09: {Name: "Razer Chroma HDK", Kind: "配件", Connection: "USB"},
	0x0F0D: {Name: "Razer Laptop Stand Chroma", Kind: "配件", Connection: "USB"},
	0x0F12: {Name: "Razer Raptor 27", Kind: "其他", Connection: "USB"},
	0x0F13: {Name: "Lian Li O11 Dynamic - Razer Edition", Kind: "配件", Connection: "USB"},
	0x0F17: {Name: "Razer Tomahawk ATX", Kind: "配件", Connection: "USB"},
	0x0F19: {Name: "Razer Kraken Kitty Edition", Kind: "耳机", Connection: "USB"},
	0x0F1A: {Name: "Razer Core X Chroma", Kind: "配件", Connection: "USB"},
	0x0F1D: {Name: "Razer Mouse Bungee V3 Chroma", Kind: "配件", Connection: "USB"},
	0x0F1F: {Name: "Razer Chroma Addressable RGB Controller", Kind: "配件", Connection: "USB"},
	0x0F20: {Name: "Razer Base Station V2 Chroma", Kind: "配件", Connection: "USB"},
	0x0F21: {Name: "Razer Thunderbolt 4 Dock Chroma", Kind: "配件", Connection: "USB"},
	0x0F26: {Name: "Razer Charging Pad Chroma", Kind: "配件", Connection: "USB"},
	0x0F2B: {Name: "Razer Laptop Stand Chroma V2", Kind: "配件", Connection: "USB"},
}
